global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "inference_service"
    static_configs:
      - targets: ["inference_service:8000"]

  - job_name: "streaming_simulator"
    static_configs:
      - targets: ["host.docker.internal:9100"]
